# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NovelDetailResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19NovelDetailResponse.proto\x12\ndmzj.novel\"g\n\x13NovelDetailResponse\x12\r\n\x05\x45rrno\x18\x01 \x01(\x05\x12\x0e\n\x06\x45rrmsg\x18\x02 \x01(\t\x12\x31\n\x04\x44\x61ta\x18\x03 \x01(\x0b\x32#.dmzj.novel.NovelDetailInfoResponse\"\xb9\x03\n\x17NovelDetailInfoResponse\x12\x0f\n\x07NovelId\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0c\n\x04Zone\x18\x03 \x01(\t\x12\x0e\n\x06Status\x18\x04 \x01(\t\x12\x1c\n\x14LastUpdateVolumeName\x18\x05 \x01(\t\x12\x1d\n\x15LastUpdateChapterName\x18\x06 \x01(\t\x12\x1a\n\x12LastUpdateVolumeId\x18\x07 \x01(\x05\x12\x1b\n\x13LastUpdateChapterId\x18\x08 \x01(\x05\x12\x16\n\x0eLastUpdateTime\x18\t \x01(\x03\x12\r\n\x05\x43over\x18\n \x01(\t\x12\x0f\n\x07HotHits\x18\x0b \x01(\x05\x12\x14\n\x0cIntroduction\x18\x0c \x01(\t\x12\r\n\x05Types\x18\r \x03(\t\x12\x0f\n\x07\x41uthors\x18\x0e \x01(\t\x12\x13\n\x0b\x46irstLetter\x18\x0f \x01(\t\x12\x14\n\x0cSubscribeNum\x18\x10 \x01(\x05\x12\x17\n\x0fRedisUpdateTime\x18\x11 \x01(\x03\x12\x39\n\x06Volume\x18\x12 \x03(\x0b\x32).dmzj.novel.NovelDetailInfoVolumeResponse\"\x92\x01\n\x1dNovelDetailInfoVolumeResponse\x12\x10\n\x08VolumeId\x18\x01 \x01(\x05\x12\x10\n\x08LnovelId\x18\x02 \x01(\x05\x12\x12\n\nVolumeName\x18\x03 \x01(\t\x12\x13\n\x0bVolumeOrder\x18\x04 \x01(\x05\x12\x0f\n\x07\x41\x64\x64time\x18\x05 \x01(\x03\x12\x13\n\x0bSumChapters\x18\x06 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NovelDetailResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOVELDETAILRESPONSE._serialized_start=41
  _NOVELDETAILRESPONSE._serialized_end=144
  _NOVELDETAILINFORESPONSE._serialized_start=147
  _NOVELDETAILINFORESPONSE._serialized_end=588
  _NOVELDETAILINFOVOLUMERESPONSE._serialized_start=591
  _NOVELDETAILINFOVOLUMERESPONSE._serialized_end=737
# @@protoc_insertion_point(module_scope)
