# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NovelChapterResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aNovelChapterResponse.proto\x12\x19\x63om.example.dmzj_api.pojo\"z\n\x14NovelChapterResponse\x12\r\n\x05\x45rrno\x18\x01 \x01(\x05\x12\x0e\n\x06\x45rrmsg\x18\x02 \x01(\t\x12\x43\n\x04\x44\x61ta\x18\x03 \x03(\x0b\x32\x35.com.example.dmzj_api.pojo.NovelChapterVolumeResponse\"\x9e\x01\n\x1aNovelChapterVolumeResponse\x12\x10\n\x08VolumeId\x18\x01 \x01(\x05\x12\x12\n\nVolumeName\x18\x02 \x01(\t\x12\x13\n\x0bVolumeOrder\x18\x03 \x01(\x05\x12\x45\n\x08\x43hapters\x18\x04 \x03(\x0b\x32\x33.com.example.dmzj_api.pojo.NovelChapterItemResponse\"X\n\x18NovelChapterItemResponse\x12\x11\n\tChapterId\x18\x01 \x01(\x05\x12\x13\n\x0b\x43hapterName\x18\x02 \x01(\t\x12\x14\n\x0c\x43hapterOrder\x18\x03 \x01(\x05\x42\x11\x42\x0fNovelChapterResb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NovelChapterResponse_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\017NovelChapterRes'
  _NOVELCHAPTERRESPONSE._serialized_start=57
  _NOVELCHAPTERRESPONSE._serialized_end=179
  _NOVELCHAPTERVOLUMERESPONSE._serialized_start=182
  _NOVELCHAPTERVOLUMERESPONSE._serialized_end=340
  _NOVELCHAPTERITEMRESPONSE._serialized_start=342
  _NOVELCHAPTERITEMRESPONSE._serialized_end=430
# @@protoc_insertion_point(module_scope)
